#!/usr/bin/env node

var createSpellPath = function( toolPath ) {
	var parts = toolPath.split( '/' )
	return parts.slice( 0, parts.length - 1 ).join( '/' )
}

var spellPath = createSpellPath( process.mainModule.filename )

requirejs = require( 'requirejs' )

requirejs.config( {
	baseUrl: spellPath + '/src',
	nodeRequire: require
} )

requirejs(
	[
		'spell/cli/developmentTool'
	],
	function(
		developmentTool
	) {
		developmentTool( process.argv, process.cwd(), spellPath )
	}
)
