#!/usr/bin/env node

var createSpellCorePath = function( toolPath ) {
	var parts = toolPath.split( '/' )
	return parts.slice( 0, parts.length - 1 ).join( '/' )
}

var spellCorePath = createSpellCorePath( process.mainModule.filename )

requirejs = require( 'requirejs' )

requirejs.config( {
	baseUrl: spellCorePath + '/src',
	nodeRequire: require
} )

requirejs(
	[
		'spell/cli/developmentTool'
	],
	function(
		developmentTool
	) {
		developmentTool( process.argv, process.cwd(), spellCorePath )
	}
)
