#!/usr/bin/env node

var createSpellPath = function( toolPath ) {
	var parts = toolPath.split( '/' )
	return parts.slice( 0, parts.length - 1 ).join( '/' )
}

requirejs = require( 'requirejs' )

requirejs.config( {
	baseUrl: '/home/martin/workspace/spell/spelljs/src',
	nodeRequire: require
} )

requirejs(
	[
		'spell/cli/developmentTool'
	],
	function(
		developmentTool
	) {
		developmentTool(
			process.argv,
			process.cwd(),
			createSpellPath( process.mainModule.filename )
		)
	}
)
