#!/bin/sh

if [ -L $0 ]; then
	FILE=$(readlink $0)
else
	FILE=$0
fi

DIRNAME=$(dirname $FILE)

if [ -f $DIRNAME/modules/nodejs/node ]; then
	NODE=$DIRNAME/modules/nodejs/node

elif [ -f $DIRNAME/node ]; then
	NODE=$DIRNAME/node

elif [ -f $DIRNAME/node.exe ]; then
	NODE=$DIRNAME/node.exe

else
	echo Error: Could not find node binary!
fi

$NODE $DIRNAME/spell.cli.js $*
